# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binassignC <- function(pos, posend, y) {
    .Call('_AlleleProfileR_binassignC', PACKAGE = 'AlleleProfileR', pos, posend, y)
}

binassignChimericC <- function(df, y) {
    .Call('_AlleleProfileR_binassignChimericC', PACKAGE = 'AlleleProfileR', df, y)
}

inssitesC <- function(allele) {
    .Call('_AlleleProfileR_inssitesC', PACKAGE = 'AlleleProfileR', allele)
}

readposendC <- function(df) {
    .Call('_AlleleProfileR_readposendC', PACKAGE = 'AlleleProfileR', df)
}

seqinsertedC <- function(seq, cigarsubs, cigarsubpos) {
    .Call('_AlleleProfileR_seqinsertedC', PACKAGE = 'AlleleProfileR', seq, cigarsubs, cigarsubpos)
}

bamQCC <- function(flag) {
    .Call('_AlleleProfileR_bamQCC', PACKAGE = 'AlleleProfileR', flag)
}

mergedSanityCheckC <- function(df) {
    .Call('_AlleleProfileR_mergedSanityCheckC', PACKAGE = 'AlleleProfileR', df)
}

getreferenceC <- function(file, chr, lower, upper) {
    .Call('_AlleleProfileR_getreferenceC', PACKAGE = 'AlleleProfileR', file, chr, lower, upper)
}

checkatgC <- function(df, gene) {
    .Call('_AlleleProfileR_checkatgC', PACKAGE = 'AlleleProfileR', df, gene)
}

checkstopC <- function(df, gene) {
    .Call('_AlleleProfileR_checkstopC', PACKAGE = 'AlleleProfileR', df, gene)
}

mutreferenceC <- function(df, cigarsubs, gene, index) {
    .Call('_AlleleProfileR_mutreferenceC', PACKAGE = 'AlleleProfileR', df, cigarsubs, gene, index)
}

snpsC <- function(df, gene, index) {
    .Call('_AlleleProfileR_snpsC', PACKAGE = 'AlleleProfileR', df, gene, index)
}

variantnameC <- function(dels, ins, snp) {
    .Call('_AlleleProfileR_variantnameC', PACKAGE = 'AlleleProfileR', dels, ins, snp)
}

generalpastelongC <- function(x, sep = "") {
    .Call('_AlleleProfileR_generalpastelongC', PACKAGE = 'AlleleProfileR', x, sep)
}

mathandC <- function(x) {
    .Call('_AlleleProfileR_mathandC', PACKAGE = 'AlleleProfileR', x)
}

mathorC <- function(x) {
    .Call('_AlleleProfileR_mathorC', PACKAGE = 'AlleleProfileR', x)
}

mathintersectC <- function(a, b, x, y) {
    .Call('_AlleleProfileR_mathintersectC', PACKAGE = 'AlleleProfileR', a, b, x, y)
}

mathrangeC <- function(start, stop, step) {
    .Call('_AlleleProfileR_mathrangeC', PACKAGE = 'AlleleProfileR', start, stop, step)
}

checknegC <- function(val) {
    .Call('_AlleleProfileR_checknegC', PACKAGE = 'AlleleProfileR', val)
}

iswithincutrangeC <- function(cutpos, range, pos, length, atgloc) {
    .Call('_AlleleProfileR_iswithincutrangeC', PACKAGE = 'AlleleProfileR', cutpos, range, pos, length, atgloc)
}

iswithincdsC <- function(atgfound, stopfound, pos, length, seqalignpos, atgloc, stoploc) {
    .Call('_AlleleProfileR_iswithincdsC', PACKAGE = 'AlleleProfileR', atgfound, stopfound, pos, length, seqalignpos, atgloc, stoploc)
}

cigarsubsC <- function(cigar) {
    .Call('_AlleleProfileR_cigarsubsC', PACKAGE = 'AlleleProfileR', cigar)
}

cigarsubstail <- function(cigarsubs) {
    .Call('_AlleleProfileR_cigarsubstail', PACKAGE = 'AlleleProfileR', cigarsubs)
}

codonsC <- function(seq, start, stop = 0L) {
    .Call('_AlleleProfileR_codonsC', PACKAGE = 'AlleleProfileR', seq, start, stop)
}

codonselectC <- function(seq, def, select = 0L, shift = 0L) {
    .Call('_AlleleProfileR_codonselectC', PACKAGE = 'AlleleProfileR', seq, def, select, shift)
}

cigarsubsdeletionsC <- function(cigarsubs, end, start = 0L, type = "cigar") {
    .Call('_AlleleProfileR_cigarsubsdeletionsC', PACKAGE = 'AlleleProfileR', cigarsubs, end, start, type)
}

cigarsubsinsertionsC <- function(cigarsubs, end, start = 0L, type = "cigar") {
    .Call('_AlleleProfileR_cigarsubsinsertionsC', PACKAGE = 'AlleleProfileR', cigarsubs, end, start, type)
}

cigarsubsSHC <- function(cigarsubs, end, start) {
    .Call('_AlleleProfileR_cigarsubsSHC', PACKAGE = 'AlleleProfileR', cigarsubs, end, start)
}

iswithininsertionC <- function(cigarsubs, pos) {
    .Call('_AlleleProfileR_iswithininsertionC', PACKAGE = 'AlleleProfileR', cigarsubs, pos)
}

readdeptc <- function(df, range) {
    .Call('_AlleleProfileR_readdeptc', PACKAGE = 'AlleleProfileR', df, range)
}

seglogoC <- function(df, frame) {
    .Call('_AlleleProfileR_seglogoC', PACKAGE = 'AlleleProfileR', df, frame)
}

